import { LoggerService } from '../mastra/services/loggerService';
import { PromptVersionRecord } from './LearningTypes';
import { LearningRepository } from './LearningRepository';

const HALLUCINATION_THRESHOLD  = 0.10; // >10% → create improved candidate
const ACCURACY_DEGRADATION_PCT = 0.05; // >5% drop → trigger optimization

export class PromptOptimizer {
  private log = new LoggerService('PromptOptimizer');

  constructor(private readonly repo: LearningRepository) {}

  /**
   * Analyzes prompt performance metrics across versions.
   * If the active version has degraded beyond thresholds, a new CANDIDATE version
   * is created with improvement annotations — ready for human review / promotion.
   */
  async optimizePrompt(
    promptName: string,
    latestMetrics: {
      accuracyRate: number;
      hallucinationRate: number;
      avgLatencyMs: number;
      sampleCount: number;
    }
  ): Promise<{ bumped: boolean; newVersion?: PromptVersionRecord }> {
    this.log.info(`[PromptOptimizer] Analyzing prompt "${promptName}"`);

    const active = await this.repo.getActivePrompt(promptName);
    if (!active) {
      this.log.warn(`[PromptOptimizer] No active prompt found for "${promptName}" — skipping`);
      return { bumped: false };
    }

    // Update sample metrics on active version
    await this.repo.savePromptVersion({
      ...active,
      accuracyRate:      latestMetrics.accuracyRate,
      hallucinationRate: latestMetrics.hallucinationRate,
      avgLatencyMs:      latestMetrics.avgLatencyMs,
      sampleCount:       (active.sampleCount ?? 0) + latestMetrics.sampleCount
    });

    const hallucinationDegraded = latestMetrics.hallucinationRate > HALLUCINATION_THRESHOLD;
    const accuracyDegraded =
      active.accuracyRate !== undefined &&
      active.accuracyRate - latestMetrics.accuracyRate > ACCURACY_DEGRADATION_PCT;

    if (!hallucinationDegraded && !accuracyDegraded) {
      this.log.info(`[PromptOptimizer] Prompt "${promptName}" v${active.version} is healthy — no bump needed`);
      return { bumped: false };
    }

    // Create a new CANDIDATE version with improvement annotations injected
    const reasons: string[] = [];
    if (hallucinationDegraded) reasons.push(`hallucination=${(latestMetrics.hallucinationRate * 100).toFixed(1)}% > threshold`);
    if (accuracyDegraded)      reasons.push(`accuracy dropped ${((active.accuracyRate! - latestMetrics.accuracyRate) * 100).toFixed(1)}%`);

    const improvedContent = [
      active.content,
      '',
      `# Optimization candidate — generated by PromptOptimizer`,
      `# Reasons: ${reasons.join('; ')}`,
      `# TODO: Review and refine this prompt before promoting to ACTIVE`,
      `# Suggested improvements:`,
      `# 1. Add explicit citation requirements to reduce hallucinations`,
      `# 2. Strengthen constraint instructions for factual grounding`,
      `# 3. Add chain-of-thought reasoning steps`
    ].join('\n');

    const candidate: PromptVersionRecord = {
      promptName,
      version:             active.version + 1,
      content:             improvedContent,
      variables:           active.variables,
      status:              'CANDIDATE',
      promotedFromVersion: active.version
    };

    const saved = await this.repo.savePromptVersion(candidate);
    this.log.info(`[PromptOptimizer] Created CANDIDATE prompt "${promptName}" v${candidate.version} — reasons: ${reasons.join('; ')}`);
    return { bumped: true, newVersion: saved };
  }

  /**
   * Promote a CANDIDATE prompt to ACTIVE and deprecate the previous ACTIVE version.
   */
  async promote(promptName: string, candidateVersion: number): Promise<void> {
    const history = await this.repo.getPromptHistory(promptName);
    const currentActive = history.find(p => p.status === 'ACTIVE');

    if (currentActive) {
      await this.repo.savePromptVersion({ ...currentActive, status: 'DEPRECATED' });
    }

    const candidate = history.find(p => p.version === candidateVersion);
    if (candidate) {
      await this.repo.savePromptVersion({ ...candidate, status: 'ACTIVE' });
      this.log.info(`[PromptOptimizer] Promoted "${promptName}" v${candidateVersion} to ACTIVE`);
    }
  }
}
