export const endpoints = {
  auth: {
    login:          '/custom/v1/auth/login',
    logout:         '/custom/v1/auth/logout',
    register:       '/custom/v1/auth/register',
    refresh:        '/custom/v1/auth/refresh',
    forgotPassword: '/custom/v1/auth/forgot-password',
    resetPassword:  '/custom/v1/auth/reset-password',
    me:             '/custom/v1/auth/me',
    sessions:       '/custom/v1/auth/sessions',
    switchOrganization: (orgId: string) => `/custom/v1/auth/switch-org/${orgId}`,
    updateProfile:  '/custom/v1/auth/profile',
  },
  incidents: {
    list:           '/custom/v1/incidents',
    create:         '/custom/v1/incidents',
    byId:           (id: string) => `/custom/v1/incidents/${id}`,
    timeline:       (id: string) => `/custom/v1/incidents/${id}/timeline`,
    notes:          (id: string) => `/custom/v1/incidents/${id}/notes`,
    resolve:        (id: string) => `/custom/v1/incidents/${id}/resolve`,
    close:          (id: string) => `/custom/v1/incidents/${id}/close`,
  },
  intelligence: {
    dashboard:       '/custom/v1/intelligence/dashboard',
    decision:        (id: string) => `/custom/v1/intelligence/decision/${id}`,
    history:         '/custom/v1/intelligence/history',
    statistics:      '/custom/v1/intelligence/statistics',
    recommendations: '/custom/v1/intelligence/recommendations',
    recompute:       '/custom/v1/intelligence/recompute',
    approve:         (id: string) => `/custom/v1/intelligence/decision/${id}/approve`,
    reject:          (id: string) => `/custom/v1/intelligence/decision/${id}/reject`,
    feedback:        (id: string) => `/custom/v1/intelligence/decision/${id}/feedback`,
  },
  runbooks: {
    list:    '/runbooks',
    create:  '/runbooks',
    byId:    (id: string) => `/runbooks/${id}`,
    execute: (id: string) => `/runbooks/${id}/execute`,
    history: (id: string) => `/runbooks/${id}/history`,
  },
  notifications: {
    list:    '/custom/v1/notifications',
    byId:    (id: string) => `/custom/v1/notifications/${id}`,
    history: '/custom/v1/notifications/history',
  },
  agents: {
    list:    '/custom/v1/agents',
    status:  '/custom/v1/agents/status',
    byId:    (id: string) => `/custom/v1/agents/${id}`,
    pause:   (id: string) => `/custom/v1/agents/${id}/pause`,
    resume:  (id: string) => `/custom/v1/agents/${id}/resume`,
    restart: (id: string) => `/custom/v1/agents/${id}/restart`,
    metrics: '/custom/v1/agents/metrics',
  },
  learning: {
    statistics:      '/custom/v1/learning/statistics',
    history:         '/custom/v1/learning/history',
    prompts:         '/custom/v1/learning/prompts',
    feedback:        '/custom/v1/learning/feedback',
    retrain:         '/custom/v1/learning/retrain',
    recommendations: '/custom/v1/learning/recommendations',
  },
  health: {
    live:         '/health',
    dependencies: '/health/dependencies',
    metrics:      '/health/metrics',
  },
  dashboard: {
    overview: '/custom/v1/dashboard/overview',
    trends:   '/custom/v1/dashboard/trends',
    severity: '/custom/v1/dashboard/severity',
    services: '/custom/v1/dashboard/services',
  },
} as const;
