CREATE TABLE IF NOT EXISTS platform_integrations (
  id UUID PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  provider VARCHAR(50) NOT NULL,
  config JSONB NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS platform_audit_logs (
  id UUID PRIMARY KEY,
  trace_id VARCHAR(100),
  actor VARCHAR(255) NOT NULL,
  action VARCHAR(255) NOT NULL,
  scope VARCHAR(100) NOT NULL,
  metadata JSONB,
  compliance_indicators JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS platform_feature_flags (
  id UUID PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  rules JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS platform_jobs (
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  payload JSONB,
  status VARCHAR(50) NOT NULL DEFAULT 'QUEUED',
  retry_count INTEGER DEFAULT 0,
  run_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_platform_audit_logs_trace_id ON platform_audit_logs(trace_id);
CREATE INDEX IF NOT EXISTS idx_platform_jobs_status_run_at ON platform_jobs(status, run_at);
