CREATE TABLE IF NOT EXISTS workflow_definitions (
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  graph JSONB NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(name, version)
);

CREATE TABLE IF NOT EXISTS workflow_executions (
  id UUID PRIMARY KEY,
  workflow_id UUID REFERENCES workflow_definitions(id),
  status VARCHAR(50) NOT NULL DEFAULT 'RUNNING',
  current_node VARCHAR(255),
  state_context JSONB,
  error_message TEXT,
  started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP WITH TIME ZONE,
  last_checkpoint_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS prompt_registry (
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  content TEXT NOT NULL,
  variables JSONB,
  status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(name, version)
);

CREATE TABLE IF NOT EXISTS model_registry (
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  provider VARCHAR(100) NOT NULL,
  capabilities JSONB,
  cost_per_1k_tokens NUMERIC(10, 6),
  latency_ms INTEGER,
  status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent_templates (
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  configuration JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_governance_logs (
  id UUID PRIMARY KEY,
  action_type VARCHAR(100) NOT NULL,
  entity_id UUID,
  details JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
