export enum IncidentStatus {
  OPEN = 'OPEN',
  INVESTIGATING = 'INVESTIGATING',
  MITIGATED = 'MITIGATED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum Priority {
  P1 = 'P1',
  P2 = 'P2',
  P3 = 'P3',
  P4 = 'P4',
}

export enum TimelineEventType {
  AI_ANALYSIS_COMPLETED = 'AI_ANALYSIS_COMPLETED',
  INCIDENT_CREATED = 'INCIDENT_CREATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  ASSIGNED = 'ASSIGNED',
  REASSIGNED = 'REASSIGNED',
  UNASSIGNED = 'UNASSIGNED',
  NOTE_ADDED = 'NOTE_ADDED',
  NOTE_UPDATED = 'NOTE_UPDATED',
  NOTE_DELETED = 'NOTE_DELETED',
  RESOLUTION_ADDED = 'RESOLUTION_ADDED',
  RESOLUTION_UPDATED = 'RESOLUTION_UPDATED',
  INCIDENT_CLOSED = 'INCIDENT_CLOSED',
}
